### ISSUE TITLE
No model for layer forbidden_arcanus:obsidian_skull

### ISSUE THREAD

**Issue by Klouver-github** [stal111/Forbidden-Arcanus#219]
the launcher denied my entry due to me not paying my taxes from 2021 and Obsidian skull having No Model for the layer
https://paste.gg/p/anonymous/898bf88d5c6f47d8b0393f8be24fb27f

**Comment by stal111** [comment]
What did you do before the crash happened?
Also are you sure that this is caused by Forbidden & Arcanus? My guess would be that it's a mod conflict since you are the only one that reported this so far.

**Comment by Klouver-github** [comment]
I took out the mod then loaded the game then added back then it worked fine, and anytime I have it installed it crashes at launch and when I take it out and re-add jt after launching it works

**Comment by stal111** [comment]
Should be fixed in 1.18.1-2.0.2

**Comment by MarkusBordihn** [comment]
Mhhh still getting the error even with forbidden_arcanus-1.18.1-2.0.2.jar

See: https://gist.github.com/MarkusBordihn/3fc54acfffd66d8fff232a268392de4b
